### ISSUE TITLE
Make keyboard parsing zoom

### ISSUE THREAD

**Issue by Alex0Blackwell** [AliShazly/sw-rasterizer#1]
We can make [keyboard_func](https://github.com/AliShazly/sw-rasterizer/blob/0b156d682ff48497bd3de5d6e9b9cdd6eac83682/src/display.c#L49) zoom a little more.

The fastest way to do it is with a nasty map thing.  
Put this at the top of `display.c`. We only want to build it once or it will be way slower.  

    #define ESC 27
    ...
    static vec3 lowercase_to_vec3[26][3] = {
        {-0.01, 0, 0},  // 'a'
        {-1}, {-1},
        {0.01, 0, 0}, {0, 0.01, 0,},  // 'd' and 'e'
        {-1}, {-1}, {-1}, {-1}, {-1}, {-1},
        {-1}, {-1}, {-1}, {-1}, {-1},
        {0, -0.01, 0},  // 'q'
        {-1},
        {0, 0, -0.01},  // 's'
        {-1}, {-1}, {-1},
        {0, 0, 0.01},  // 'w'
        {-1}, {-1}, {-1}
    };

Now the logic becomes super easy. 

    /**
     * Exit program when escape is pressed.
     * Handle camera movement input.
     */
    void keyboard_parsing(unsigned char c) {
        char lowercase_char = c - 'a';
        vec3 *offset;
        
        if(c == ESC)
            exit(0);
        offset = lowercase_to_vec3[lowercase_char];
        if(*offset != -1)
            move_camera(CTX, *offset);
    }

The old implementation would not be able to make use of [branch prediction](https://en.wikipedia.org/wiki/Branch_predictor), but this should just step forward like an idiot and cache it on the way.  

Also I have no idea if this works, I haven't run it, but it should be pretty close.

**Comment by AliShazly** [comment]
fixed in: 83e94e8716a39c01a1a662d96aba44d8e300a5f1
we're absolutely _zoomin_,it only took me a year
